services:
  - type: web
    name: resume-fixer-backend
    env: python
    runtime: python-3.9.6
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libfreetype6-dev libjpeg-dev poppler-utils
      pip install -r requirements.txt
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 60"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 5000
    autoDeploy: true