services:
  - type: web
    name: resumefixerpro-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: OPENAI_API_KEY
        sync: false