services:
  - type: web
    name: resume-fixer-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false