module.exports = {
  content: [
    "./styles/input.css",
    "./**/*.html",
    "./**/*.js",
    "./**/*.php",
    "./**/*.jsx",
    "./**/*.ts",
    "./**/*.tsx",
  ],
  safelist: [
    'text-center',
    'text-left',
    'text-right',
    'bg-white',
    'bg-gray-100',
    'bg-blue-500',
    'text-blue-500',
    'text-green-500',
    'text-red-500',
    'font-bold',
    'rounded-full',
    'px-4',
    'py-2',
    'mt-4',
    'mb-4',
    'w-full',
    'max-w-4xl',
    'mx-auto',
    'hidden',
    'block',
    'flex',
    'items-center',
    'justify-center',
    'shadow-xl',
    'hover:bg-blue-600',
    'transition',
    'duration-300',
    'ease-in-out',
    // yaha tum WordPress wale HTML me jo bhi tailwind classes use kar rahe ho wo manually daal sakte ho
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
